apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "spa.fullname" . }}-cdn-purge"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: cdn-purge
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - >
              echo "Purging Cloudflare cache..." &&
              curl -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/purge_cache"
              -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}"
              -H "Content-Type: application/json"
              --data '{"purge_everything":true}'
          env:
            - name: CLOUDFLARE_ZONE_ID
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: zone_id
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: api_token
      restartPolicy: Never
